services:
  postgres:
    container_name: nest-clean-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
